openapi: "3.1.0"
info:
  title: Zotero API Plugin
  description: >
    A plugin to interact with any user's Zotero library using their own API key.
    The plugin retrieves everything the user can see: personal libraries, group/shared collections,
    items, notes, and PDF content. Use the /all_collections endpoint by default when asking
    "What’s in my library?" or similar.
  version: "1.0.0"

servers:
  - url: https://zotero-gpt.onrender.com

paths:
  /ping:
    get:
      operationId: pingServer
      summary: Ping the server and get user ID from Zotero
      parameters:
        - name: api_key
          in: query
          description: Zotero API key of the user
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful ping

  /all_collections:
    get:
      operationId: getAllCollections
      summary: List all user collections from both personal and group libraries
      description: |
        Retrieves everything the user has access to in Zotero—personal collections and shared group libraries.
        Supports nested structures. Use to answer questions like “What’s in my library?” or “Show my folders”.
      parameters:
        - name: api_key
          in: query
          description: Zotero API key of the user
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Combined list of personal and group collections

  /items:
    get:
      operationId: searchItems
      summary: Search for items by keyword or within a collection
      description: >
        Searches items in the user's Zotero collections (personal and group). Can filter by a named or nested collection.
        Includes fuzzy matching and fallback to broader queries if no direct match is found.
      parameters:
        - name: api_key
          in: query
          description: Zotero API key
          required: true
          schema:
            type: string
        - name: q
          in: query
          description: Keyword to search for (title, abstract, or author)
          required: false
          schema:
            type: string
        - name: collection
          in: query
          description: Collection name or key to restrict the search
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Matching Zotero items

  /notes:
    get:
      operationId: getNotes
      summary: Get notes for a specific Zotero item
      description: Fetches notes attached to a Zotero item (either directly or via title search).
      parameters:
        - name: api_key
          in: query
          description: Zotero API key
          required: true
          schema:
            type: string
        - name: itemKey
          in: query
          description: The Zotero item key
          required: false
          schema:
            type: string
        - name: q
          in: query
          description: Alternative title-based lookup if itemKey is not known
          required: false
          schema:
            type: string
        - name: collection
          in: query
          description: Optional collection scope
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Notes found for the item

  /read_pdf:
    get:
      operationId: readPdf
      summary: Extract text from a PDF in Zotero
      description: >
        Extracts readable text from a PDF stored in Zotero.
        Accepts an itemKey or resolves by title within an optional collection context.
      parameters:
        - name: api_key
          in: query
          description: Zotero API key
          required: true
          schema:
            type: string
        - name: itemKey
          in: query
          description: The Zotero item key (PDF attachment or parent item)
          required: false
          schema:
            type: string
        - name: title
          in: query
          description: Alternative way to resolve item by title
          required: false
          schema:
            type: string
        - name: collection
          in: query
          description: Optional collection context to disambiguate
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Extracted PDF text content

  /summarize_collection:
    get:
      operationId: summarizeCollection
      summary: Summarize a Zotero collection including subcollections
      description: >
        Resolves a top-level collection and gathers all items from that collection and its subcollections.
        Then reads PDFs (if available), extracts text, identifies shared themes, and surfaces any divergent viewpoints.
      parameters:
        - name: api_key
          in: query
          description: Zotero API key
          required: true
          schema:
            type: string
        - name: collection
          in: query
          description: Name of the collection (folder) to summarize
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Collection summary with themes, items, and any content divergence



  /collection_tree_preview:
    get:
      operationId: previewCollectionTree
      summary: Get formatted hierarchical preview of all Zotero collections
      description: |
        Returns a plain-text indented tree of all collections and subcollections, including group and personal libraries.
        Useful for visualizing nested folder structures.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
          description: Zotero API key
      responses:
        "200":
          description: Tree-formatted text of collections
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
        "400":
          description: Missing API key
        "500":
          description: Server error or Zotero API failure

    

# Optional for future:
#  /extract_themes:
#    post:
#      operationId: extractThemes
#      summary: Extract themes and divergence from provided texts
#      description: >
#        Accepts a list of raw texts and returns high-level themes and any notable divergence between them.
#        Useful for external tools that want to reuse the summarization logic without calling /summarize_collection.
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              type: object
#              properties:
#                texts:
#                  type: array
#                  items:
#                    type: string
#      responses:
#        "200":
#          description: Thematic summary and divergence analysis
